# Generated by Django 3.2.7 on 2021-10-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(max_length=25, verbose_name='city'),
        ),
    ]
